function myGUI

    % Create figure
    h.f = figure('units','pixels',...
                 'toolbar','none','menu','none','name','Choose figures to save','NumberTitle','Off');

    % Create checkboxes
    h.c(1) = uicontrol('style','checkbox','units','pixels',...
        'position',[10,370,200,15],'string','rlvsstimno');
    h.c(2) = uicontrol('style','checkbox','units','pixels',...
        'position',[10,340,200,15],'string','silvsstimno');
    h.c(3) = uicontrol('style','checkbox','units','pixels',...
        'position',[10,310,200,15],'string','rlvssil');
    h.c(4) = uicontrol('style','checkbox','units','pixels',...
        'position',[10,280,200,15],'string','IBI_pre');
    h.c(5) = uicontrol('style','checkbox','units','pixels',...
        'position',[10,250,200,15],'string','IBI_post');
    h.c(6) = uicontrol('style','checkbox','units','pixels',...
        'position',[10,220,200,15],'string','respdist');
    h.c(7) = uicontrol('style','checkbox','units','pixels',...
        'position',[10,190,200,15],'string','IBI_rec_pre');
    h.c(8) = uicontrol('style','checkbox','units','pixels',...
        'position',[10,160,200,15],'string','IBI_rec_post');
    h.c(9) = uicontrol('style','checkbox','units','pixels',...
        'position',[10,130,200,15],'string','ISI_rec_pre');
    h.c(10) = uicontrol('style','checkbox','units','pixels',...
        'position',[10,100,200,15],'string','ISI_rec_post');





    h.c(11) = uicontrol('style','checkbox','units','pixels',...
        'position',[300,370,200,15],'string','nSp_diffcases');
    h.c(12) = uicontrol('style','checkbox','units','pixels',...
        'position',[300,340,200,15],'string','spon_dist');
    h.c(13) = uicontrol('style','checkbox','units','pixels',...
        'position',[300,310,200,15],'string','qtab-1');
    h.c(14) = uicontrol('style','checkbox','units','pixels',...
        'position',[300,280,200,15],'string','qtab-2');
    h.c(15) = uicontrol('style','checkbox','units','pixels',...
        'position',[300,250,200,15],'string','qtab-3');
    h.c(16) = uicontrol('style','checkbox','units','pixels',...
        'position',[300,220,200,15],'string','IstimI_dist');
    h.c(17) = uicontrol('style','checkbox','units','pixels',...
        'position',[300,190,200,15],'string','IstimI_evol');
    h.c(18) = uicontrol('style','checkbox','units','pixels',...
        'position',[300,160,200,15],'string','stimfreqvstime');
    h.c(19) = uicontrol('style','checkbox','units','pixels',...
        'position',[300,130,200,15],'string','trials_all');
    h.c(20) = uicontrol('style','checkbox','units','pixels',...
        'position',[300,100,200,15],'string','errvslpb');
    h.c(21) = uicontrol('style','checkbox','units','pixels',...
        'position',[300,70,200,15],'string','all');
    h.c(22) = uicontrol('style','checkbox','units','pixels',...
        'position',[300,40,200,15],'string','none');


    % Create OK pushbutton   
    h.p = uicontrol('style','pushbutton','units','pixels',...
                    'position',[60,50,70,20],'string','OK',...
                    'callback',@p_call);

        % Pushbutton callback
        function p_call(varargin)
            vals = get(h.c,'Value');
            checked = find([vals{:}]);
            if isempty(checked)
                checked = 'none';
            end
            disp(checked)
            fig_handles = {'rlvsstimno', ...
                           'silvsstimno',...
                           'rlvssil',...
                           'IBI_pre',...
                           'IBI_post',...
                           'respdist',...
                           'IBI_rec_pre',...
                           'IBI_rec_post',...
                           'ISI_rec_pre',...
                           'ISI_rec_post',...
                           'nSP_diffcases',...
                           'spon_dist',...
                           'qtab-1',...
                           'qtab-2',...
                           'qtab-3',...
                           'IstimI-dist',...
                           'IstimI_evol',...
                           'stimfreqvstime',...
                           'trials_all',...
                           'errvslpb'
                           };
                                 
            close(h.f);
            
            
        end

end