function fig = mea88_style(varargin)


%varargin can be a axis handle, then the 8x8 plot of the mea layout is done
%in this axes
%different arguments can be given
%e.g. the electrode position, in columns row manner (from bottom left axis origin,
%as wel as the color to mark the given channels

%the varargin should include
% 'axis_handle'
% 'el_pos', a length-2 vector
% 'el_color', a string for the color 




markersize = 15;
markerfacecolor ='none';
linewidth = 0.5;
color = 'k';



pvpmod(varargin)

%pvpmod(varargin)
load meadot_grid

if exist('axis_handle')
    h0 = get(axis_handle,'parent');
    h1 = axis_handle;
    set(h1,'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat2, ...
        'PlotBoxAspectRatioMode','manual', ...
        'Visible','off', ...
        'WarpToFill','off', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
        hold on
else
    h0 = figure('Color',[0.8 0.8 0.8], ...
        'Colormap',mat0, ...
        'PaperType','a4letter', ...
        'PointerShapeCData',mat1, ...
        'Position',[360 544 560 420]);  
    h1 = axes('Parent',h0, ...
        'Box','on', ...
        'CameraUpVector',[0 1 0], ...
        'Color',[1 1 1], ...
        'ColorOrder',mat2, ...
        'PlotBoxAspectRatioMode','manual', ...
        'Visible','off', ...
        'WarpToFill','off', ...
        'XColor',[0 0 0], ...
        'YColor',[0 0 0], ...
        'ZColor',[0 0 0]);
end

h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'LineStyle','none', ...
	'Marker','o', ...
	'XData',mat3, ...
	'YData',mat4);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'LineStyle','none', ...
	'Marker','o', ...
	'XData',mat5, ...
	'YData',mat6);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'LineStyle','none', ...
	'Marker','o', ...
	'XData',mat7, ...
	'YData',mat8);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'LineStyle','none', ...
	'Marker','o', ...
	'XData',mat9, ...
	'YData',mat10);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'LineStyle','none', ...
	'Marker','o', ...
	'XData',mat11, ...
	'YData',mat12);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'LineStyle','none', ...
	'Marker','o', ...
	'XData',mat13, ...
	'YData',mat14);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'LineStyle','none', ...
	'Marker','o', ...
	'XData',mat15, ...
	'YData',mat16);
h2 = line('Parent',h1, ...
	'Color',[0 0 0], ...
	'LineStyle','none', ...
	'Marker','o', ...
	'XData',mat17, ...
	'YData',mat18);
if nargout > 0, fig = h0; end

set(findobj(h1, 'type', 'line'), 'markersize', markersize, 'markerfacecolor', markerfacecolor, ...
   'color', color, 'linewidth', linewidth);
if ~exist('axis_handle')
    axis equal
end

if exist('el_pos')
    hold on
    plot(el_pos(1),el_pos(2),'o','markersize', markersize, 'markerfacecolor', el_color, ...
   'color', el_color, 'linewidth', linewidth);
end






